"use client";

/**
 * A dosha as a mark: its element drawn on a ground mixed from its own colour.
 *
 * THE COLOUR IS BEHIND THE GLYPH, NEVER INSIDE IT. The three glyphs are icons
 * like every other glyph in the sprite — `currentColor`, monoline, no fill —
 * and a `<use>` into an external sprite reaches a shadow tree that host CSS
 * cannot paint. So the disc carries the colour and the glyph inherits it,
 * both mixed from one semantic token (`--cw-sem-dosha-*`) rather than from a
 * second palette that would have to be re-tuned every time the gamma moves.
 *
 * The specimen is `guidelines/dosha-marks.card.html` in the Claude Design
 * mirror, generated by `scripts/icons-preview.mjs`; the recipe here and the
 * recipe there are the same two stops and must stay that way.
 */

import { Icon } from "@/components/Icon";
import styles from "@/components/platform/PlatformSurfaceStyles";
import type { BaseDosha } from "@/lib/dosha/doshaTest";

/** The glyph sits at 46% of the disc — the ratio the specimen is drawn at. */
const GLYPH_RATIO = 0.46;

/**
 * Below this the ground is dropped and the glyph stands alone: a tint under
 * 32px reads as a smudge rather than as a disc, which is the one rule on the
 * specimen card that is about size and not about colour.
 */
const GROUND_MIN_SIZE = 32;

export function DoshaMark({
  dosha,
  size = 56,
  label,
}: {
  dosha: BaseDosha;
  /** Diameter of the ground in px. */
  size?: number;
  /** Give it a name and it becomes an image; omit and it is decorative. */
  label?: string;
}) {
  const withGround = size >= GROUND_MIN_SIZE;
  const glyph = Math.round(withGround ? size * GLYPH_RATIO : size);

  return (
    <span
      className={withGround ? styles.doshaMark : styles.doshaMarkBare}
      data-dosha={dosha}
      style={withGround ? { width: size, height: size } : undefined}
      role={label ? "img" : undefined}
      aria-label={label}
      aria-hidden={label ? undefined : true}
    >
      <Icon className={styles.doshaMarkGlyph} name={dosha} size={glyph} />
    </span>
  );
}
