/**
 * Every string the profile fold prints, in both languages.
 *
 * Split out of AuthorProfileFold.tsx (1,573 lines) on 2026-09-11; nothing inside any declaration changed.
 */

export const STRINGS = {
  uk: {
    title: "Профіль автора",
    lead: "Ім'я, фото і біографія тут — вони підуть на кожен ваш курс і, якщо публічний, на власну сторінку.",
    name: "Ім'я",
    role: "Роль (один рядок)",
    bio: "Біографія",
    quote: "Цитата від першої особи",
    credentials: "Досягнення",
    credentialAdd: "Додати досягнення",
    credentialRemove: "Прибрати досягнення",
    credentialRequired: "Перший рядок потрібен, щоб сторінку було видно",
    credentialsHint: "Перше — головне: саме воно стоїть бейджем на картці.",
    facts: "Головні факти про себе",
    factsHint: "До 6 — перші три показуються на картці.",
    factAdd: "Додати факт",
    factRemove: "Прибрати факт",
    profileBlocks: "Блоки сторінки автора",
    profileBlockAdd: "Додати блок",
    profileBlockRemove: "Прибрати блок",
    profileBlockKind: "Формат блока",
    profileBlockLabel: "Надзаголовок",
    profileBlockTitle: "Заголовок",
    profileBlockBody: "Текст блока",
    profileBlockItems: "Пункти — кожен з нового рядка",
    profileBlockText: "Текст",
    profileBlockList: "Список",
    profileBlockTimeline: "Шлях / хронологія",
    experienceBadge: "Бейдж досвіду",
    requiredForCard: "Обов’язково для публічної картки",
    consultation: "Консультація",
    consultationEnabled: "Приймаю запити на консультацію",
    consultationPoints: "Головні пункти",
    consultationPointsHint: "До 3.",
    consultationPointAdd: "Додати пункт",
    consultationPointRemove: "Прибрати пункт",
    photo: "Фото",
    photoUpload: "Завантажити фото",
    photoReplace: "Замінити фото",
    photoRemove: "Прибрати фото",
    photoUploading: "Завантаження…",
    /* ONE MESSAGE PER REASON. The upload used to answer every failure with the
       form's generic «Не вдалося зберегти» — which on a phone, where the file
       is large and the connection is not, read as "it silently did nothing".
       The route already distinguishes these; the form now repeats it. */
    uploadTooLarge: "Файл завеликий — до 20 МБ.",
    uploadBadType: "Такий формат не підтримується. JPEG, PNG, WebP, AVIF або GIF.",
    uploadTooOften: "Забагато завантажень поспіль. Спробуйте за хвилину.",
    uploadFailed: "Не вдалося завантажити фото. Спробуйте ще раз.",
    sectionYou: "Ви",
    sectionYouNote: "Фото, ім'я і роль — друкуються під кожним вашим курсом, навіть поки сторінка прихована.",
    sectionAbout: "Про себе",
    sectionAboutNote: "Текст і факти. Перші три факти та бейджі показуються на картці автора.",
    sectionPage: "Ваша сторінка",
    sectionPageNote: "Чи є вона, за якою адресою, і з чого складається.",
    photoAltRequired: "Без опису фото не збережеться",
    consultationTitleLabel: "Назва консультації",
    consultationSummaryLabel: "Кому і з чим допомагаю",
    consultationContactLabel: "Посилання для домовленості",
    consultationRequired: "Потрібно, поки консультації увімкнено",
    /* The stage, not the frame: what the hand moves here is the window over the
       whole photograph, and telling someone to drag the photo would be telling
       them to drag the one thing on this screen that stays still. */
    cropFocus: "Ціла світлина. Перетягуйте рамку або використовуйте стрілки. Ctrl і колесо — масштаб.",
    cropOpen: "Обрати кадр",
    cropDone: "Готово",
    cropZoom: "Масштаб",
    cropFocusAt: "Фокус: {x}% по горизонталі, {y}% по вертикалі",
    nameRequired: "Ім'я потрібне завжди — воно стоїть під кожним курсом",
    blockNumber: "Блок",
    photoAlt: "Опис фото (для читачів екрана)",
    mediaDrop: "Відпустіть, щоб завантажити",
    photoCropCardTitle: "Картка",
    photoCropCardNote: "Головна · консультації · директорія авторів",
    /* Named by its job, not by its shape (2026-09-06): portraits left the
       circle, and a caption that says «кругла» over a soft-rect preview teaches
       the author a shape the product no longer draws. */
    photoCropAvatarTitle: "Аватарка",
    photoCropAvatarNote: "Сторінка автора · автор курсу",
    photoCropCenter: "По центру",
    background: "Фон публічної сторінки",
    backgroundHint: "Друкується тільки на вашій сторінці, під портретом.",
    backgroundUpload: "Завантажити фон",
    backgroundReplace: "Замінити фон",
    backgroundRemove: "Прибрати фон",
    listed: "Публічна сторінка",
    listedOn: "Сторінку /expert видно всім",
    listedOff: "Сторінка прихована — видно лише в описі курсу",
    slug: "Адреса сторінки",
    save: "Зберегти",
    saving: "Зберігаємо…",
    saved: "Збережено",
    viewPublic: "Відкрити",
    error: "Не вдалося зберегти. Перевірте поля і спробуйте ще раз.",
  },
  en: {
    title: "Author profile",
    lead: "Name, photo and bio live here — they follow every course you write, and your own page if it's public.",
    name: "Name",
    role: "Role (one line)",
    bio: "Bio",
    quote: "A quote, in your own voice",
    credentials: "Credentials",
    credentialAdd: "Add credential",
    credentialRemove: "Remove credential",
    credentialRequired: "The first line is needed for the page to be visible",
    credentialsHint: "The first one is the main one — it stands as the badge on your card.",
    facts: "Key facts about you",
    factsHint: "Up to 6 — the first three show on the card.",
    factAdd: "Add fact",
    factRemove: "Remove fact",
    profileBlocks: "Author page blocks",
    profileBlockAdd: "Add block",
    profileBlockRemove: "Remove block",
    profileBlockKind: "Block format",
    profileBlockLabel: "Eyebrow",
    profileBlockTitle: "Heading",
    profileBlockBody: "Block text",
    profileBlockItems: "Items — one per line",
    profileBlockText: "Text",
    profileBlockList: "List",
    profileBlockTimeline: "Path / timeline",
    experienceBadge: "Experience badge",
    requiredForCard: "Required for the public card",
    consultation: "Consultation",
    consultationEnabled: "Accept consultation requests",
    consultationPoints: "Key points",
    consultationPointsHint: "Up to 3.",
    consultationPointAdd: "Add point",
    consultationPointRemove: "Remove point",
    photo: "Photo",
    photoUpload: "Upload photo",
    photoReplace: "Replace photo",
    photoRemove: "Remove photo",
    photoUploading: "Uploading…",
    uploadTooLarge: "File is too large — 20 MB maximum.",
    uploadBadType: "That format is not supported. JPEG, PNG, WebP, AVIF or GIF.",
    uploadTooOften: "Too many uploads in a row. Try again in a minute.",
    uploadFailed: "Could not upload the photo. Try again.",
    sectionYou: "You",
    sectionYouNote: "Photo, name and role — printed under every course you write, even while your page is hidden.",
    sectionAbout: "About you",
    sectionAboutNote: "The text and the facts. The first three facts and both badges show on your card.",
    sectionPage: "Your page",
    sectionPageNote: "Whether it exists, at what address, and what it is made of.",
    photoAltRequired: "Without a description the photo is not saved",
    consultationTitleLabel: "Consultation title",
    consultationSummaryLabel: "Who you help, and with what",
    consultationContactLabel: "Link for arranging it",
    consultationRequired: "Needed while consultations are on",
    cropFocus: "The whole photograph. Drag the frame, or use the arrow keys. Ctrl and the wheel zoom.",
    cropOpen: "Choose the frame",
    cropDone: "Done",
    cropZoom: "Zoom",
    cropFocusAt: "Focus: {x}% across, {y}% down",
    nameRequired: "Always needed — it prints under every course",
    blockNumber: "Block",
    photoAlt: "Photo description (for screen readers)",
    mediaDrop: "Drop to upload",
    photoCropCardTitle: "Card",
    photoCropCardNote: "Home · consultations · author directory",
    photoCropAvatarTitle: "Avatar",
    photoCropAvatarNote: "Author's own page · course byline",
    photoCropCenter: "Centre",
    background: "Public page background",
    backgroundHint: "Prints on your own page only, behind the portrait.",
    backgroundUpload: "Upload background",
    backgroundReplace: "Replace background",
    backgroundRemove: "Remove background",
    listed: "Public page",
    listedOn: "The /expert page is visible to everyone",
    listedOff: "Hidden — shown only as a course byline",
    slug: "Page address",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    viewPublic: "Preview",
    error: "Could not save. Check the fields and try again.",
  },
} as const;
