import type { ProfileCopy, ProfileLang } from "./types";

type ProfileCopyCounts = {
  productPurchases: number;
};

export function getProfileCopy(lang: ProfileLang, counts: ProfileCopyCounts): ProfileCopy {
  const { productPurchases } = counts;

  if (lang === "en") {
    return {
      profile: "Account",
      // Shown when Google returned no name/email on the account.
      fallbackName: "Your CenterWay account",
      fallbackEmail: "CenterWay account",
      loadingTitle: "Loading your data",
      loadingLead: "We are gathering your dosha result, programs, products, and contact fields.",
      authTitle: "Sign in",
      authLead: "Your dosha result, programs and access are waiting here.",
      authEmailTitle: "Sign in by email",
      authEmailLead: "We will send a code to your address.",
      authEmailStaffHint: "The work address your role is attached to.",
      signIn: "Sign in",
      takeDosha: "Take the dosha test",
      badge: "Account · Dosha · Programs",
      dosha: "Dosha",
      activePrograms: "Active programs",
      products: "Products",
      contacts: "Contacts",
      contactsReady: "Saved",
      contactsMissing: "Add your details",
      noDosha: "Not defined yet",
      noPrograms: "None yet",
      hasPrograms: "In progress",
      hasProducts: "Added to account",
      noProducts: "None yet",
      heroViewDosha: "View dosha result",
      signOut: "Sign out",
      doshaCurrent: "Current result",
      doshaResultPrefix: "Result",
      doshaCompletedPrefix: "Completed",
      completedShort: "Completed",
      retakeTest: "Retake the test",
      doshaEmptyLead:
        "There is no completed dosha test in this account yet, so the personal state map is not assembled.",
      startTest: "Start the dosha test",
      routeSummaryLabel: "At a glance",
      routeSummaryTitle: "Your account at a glance",
      summaryActivePrograms: "Active programs",
      summaryCompletedPrograms: "Completed programs",
      summaryProducts: "Products in account",
      summaryProductsValue: productPurchases > 0 ? `${productPurchases}` : "None yet",
      programsLabel: "Programs",
      programsTitle: "Active and completed programs",
      activeProgramLabel: "Active program",
      completedProgramLabel: "Completed program",
      routeStarted: "Program started",
      purchasedAt: "Purchase date",
      programProgressNote:
        "Program access and status stay visible here, and detailed lesson progress gathers into this map as the program unfolds.",
      programAccessManual: "Access is confirmed separately",
      programAccessNoToken: "This program was issued without a separate access token",
      noProgramsLead: "There are no programs linked to this account yet.",
      productsTitle: "Purchased items",
      productsLead: "Everything you have purchased and the current state of each access.",
      productLabel: "Product",
      price: "Price",
      noProductsLead: "There are no purchased products linked to this account yet.",
      progressLabel: "Progress",
      progressTitle: "Program progress",
      progressLead:
        "This section assembles your active programs, completed steps, and the next relevant step inside the platform.",
      contactsTitle: "Saved contact fields",
      name: "Name",
      email: "Email",
      phone: "Phone",
      telegram: "Telegram",
      unavailableTitle: "Account is temporarily unavailable",
      unavailableLead: "Personal account access is unavailable in this build.",
      errorTitle: "Could not assemble the account",
      errorFallback: "Please refresh the page a bit later.",
      emptyValue: "—",
      doshaLabels: { vata: "Vata", pitta: "Pitta", kapha: "Kapha" },
    };
  }

  return {
    profile: "Кабінет",
    fallbackName: "Ваш кабінет CenterWay",
    fallbackEmail: "Акаунт CenterWay",
    loadingTitle: "Завантажуємо ваші дані",
    loadingLead: "Збираємо ваш результат тесту доші, програми, продукти і контакти.",
    authTitle: "Вхід у кабінет",
    authLead: "Результат доша-тесту, програми і доступи чекають тут.",
    authEmailTitle: "Вхід через пошту",
    authEmailLead: "Надішлемо код на вашу адресу.",
    authEmailStaffHint: "Робоча адреса, до якої прив\u2019язана ваша роль.",
    signIn: "Увійти",
    takeDosha: "Пройти доша-тест",
    badge: "Кабінет · Доша · Програми",
    dosha: "Доша",
    activePrograms: "Активні програми",
    products: "Продукти",
    contacts: "Контакти",
    contactsReady: "Заповнені",
    contactsMissing: "Додайте дані",
    noDosha: "Ще не визначено",
    noPrograms: "Поки немає",
    hasPrograms: "Є програма",
    hasProducts: "Додані до кабінету",
    noProducts: "Поки немає",
    heroViewDosha: "Подивитися результат доші",
    signOut: "Вийти",
    doshaCurrent: "Поточний результат",
    doshaResultPrefix: "Результат",
    doshaCompletedPrefix: "Завершено",
    completedShort: "Пройдено",
    retakeTest: "Перепройти тест",
    doshaEmptyLead:
      "Ви ще не проходили тест доші. Він займає кілька хвилин і допомагає побачити ваш поточний стан і перший крок.",
    startTest: "Почати доша-тест",
    routeSummaryLabel: "Коротко",
    routeSummaryTitle: "Коротко про ваш кабінет",
    summaryActivePrograms: "Активні програми",
    summaryCompletedPrograms: "Завершені програми",
    summaryProducts: "Продукти в кабінеті",
    summaryProductsValue: productPurchases > 0 ? `${productPurchases}` : "Поки немає",
    programsLabel: "Програми",
    programsTitle: "Активні та завершені програми",
    activeProgramLabel: "Активна програма",
    completedProgramLabel: "Завершена програма",
    routeStarted: "Старт програми",
    purchasedAt: "Дата покупки",
    programProgressNote:
      "Тут видно доступ і стан кожної програми. Прогрес по уроках зʼявляється тут же, щойно ви їх проходите.",
    programAccessManual: "Доступ підтверджено окремо",
    programAccessNoToken: "Програма була оформлена без окремого токена доступу",
    noProgramsLead: "У кабінеті поки немає програм.",
    productsTitle: "Придбані товари",
    productsLead: "Усе, що ви придбали, і стан доступу до кожного.",
    productLabel: "Продукт",
    price: "Сума",
    noProductsLead: "У кабінеті поки немає придбаних продуктів.",
    progressLabel: "Поступ",
    progressTitle: "Проходження програм",
    progressLead: "Тут видно, де ви зараз: активні програми, пройдені етапи і наступний крок.",
    contactsTitle: "Ваші контакти",
    name: "Ім’я",
    email: "Email",
    phone: "Телефон",
    telegram: "Telegram",
    unavailableTitle: "Кабінет тимчасово недоступний",
    unavailableLead: "Кабінет зараз не відкривається. Спробуйте трохи пізніше.",
    errorTitle: "Не вдалося відкрити кабінет",
    errorFallback: "Спробуйте оновити сторінку трохи пізніше.",
    emptyValue: "—",
    doshaLabels: { vata: "Вата", pitta: "Пітта", kapha: "Капха" },
  };
}
