import type { ProfileCopy, ProfileLang } from "./types";

type ProfileCopyCounts = {
  activePrograms: number;
  completedPrograms: number;
  productPurchases: number;
};

export function getProfileCopy(
  lang: ProfileLang,
  counts: ProfileCopyCounts,
): ProfileCopy {
  const {
    activePrograms,
    completedPrograms,
    productPurchases,
  } = counts;

  if (lang === "en") {
    return {
      profile: "Profile",
      loadingTitle: "Loading your data",
      loadingLead: "We are gathering your dosha result, programs, products, and contact fields.",
      authTitle: "Sign in to view your route",
      authLead: "Your profile keeps the dosha result, program access, support formats, and contact details together.",
      signIn: "Sign in with Google",
      returnHome: "Return home",
      takeDosha: "Take the dosha test",
      badge: "Profile · Dosha · Route",
      dosha: "Dosha",
      activePrograms: "Active programs",
      products: "Products",
      contacts: "Contacts",
      contactsReady: "Saved",
      contactsMissing: "Add your details",
      noDosha: "Not defined yet",
      noPrograms: "None yet",
      hasPrograms: "In progress",
      hasProducts: "Added to profile",
      noProducts: "None yet",
      heroViewDosha: "View dosha result",
      signOut: "Sign out",
      doshaCurrent: "Current result",
      doshaResultPrefix: "Result",
      doshaCompletedPrefix: "Completed",
      completedShort: "Completed",
      retakeTest: "Retake the test",
      doshaEmptyLead: "There is no completed dosha test in this profile yet, so the personal state map is not assembled.",
      startTest: "Start the dosha test",
      routeSummaryLabel: "Route",
      routeSummaryTitle: "Current route summary",
      summaryActivePrograms: "Active programs",
      summaryCompletedPrograms: "Completed programs",
      summaryProducts: "Products in profile",
      summaryActiveProgramsValue: activePrograms > 0 ? `${activePrograms}` : "None yet",
      summaryCompletedProgramsValue: completedPrograms > 0 ? `${completedPrograms}` : "None yet",
      summaryProductsValue: productPurchases > 0 ? `${productPurchases}` : "None yet",
      programsLabel: "Programs",
      programsTitle: "Active and completed routes",
      activeProgramLabel: "Active program",
      completedProgramLabel: "Completed route",
      routeStarted: "Route started",
      purchasedAt: "Purchase date",
      accessStatus: "Access status",
      programProgressNote: "Route access and status stay visible here, and detailed lesson progress gathers into this map as the route unfolds.",
      programAccessManual: "Access is confirmed separately",
      programAccessNoToken: "This route was issued without a separate access token",
      noProgramsLead: "There are no programs linked to this profile yet.",
      productsTitle: "Purchased support formats",
      productLabel: "Product",
      price: "Price",
      productNoAccess: "Access is being prepared",
      noProductsLead: "There are no purchased products linked to this profile yet.",
      progressLabel: "Progress",
      progressTitle: "Program progress",
      progressLead: "This section assembles your active routes, completed steps, and the next relevant movement inside the platform.",
      contactsTitle: "Saved contact fields",
      name: "Name",
      email: "Email",
      phone: "Phone",
      telegram: "Telegram",
      unavailableTitle: "Profile is temporarily unavailable",
      unavailableLead: "Personal profile access is unavailable in this build.",
      errorTitle: "Could not assemble the profile",
      errorFallback: "Please refresh the page a bit later.",
      emptyValue: "—",
      doshaLabels: { vata: "Vata", pitta: "Pitta", kapha: "Kapha" },
    };
  }

  return {
    profile: "Профіль",
    loadingTitle: "Завантажуємо ваші дані",
    loadingLead: "Підтягуємо результат доша-тесту, програми, продукти і ваші контактні поля.",
    authTitle: "Увійдіть, щоб побачити свій маршрут",
    authLead: "У профілі зберігаються результат доша-тесту, доступи до програм, формати підтримки і контактна інформація.",
    signIn: "Увійти через Google",
    returnHome: "Повернутися на головну",
    takeDosha: "Пройти доша-тест",
    badge: "Профіль · Доша · Маршрут",
    dosha: "Доша",
    activePrograms: "Активні програми",
    products: "Продукти",
    contacts: "Контакти",
    contactsReady: "Заповнені",
    contactsMissing: "Додайте дані",
    noDosha: "Ще не визначено",
    noPrograms: "Поки немає",
    hasPrograms: "Є маршрут",
    hasProducts: "Додані до профілю",
    noProducts: "Поки немає",
    heroViewDosha: "Подивитися результат доші",
    signOut: "Вийти",
    doshaCurrent: "Поточний результат",
    doshaResultPrefix: "Результат",
    doshaCompletedPrefix: "Завершено",
    completedShort: "Пройдено",
    retakeTest: "Перепройти тест",
    doshaEmptyLead: "У профілі ще немає завершеного доша-тесту, тому персональна карта стану поки не зібрана.",
    startTest: "Почати доша-тест",
    routeSummaryLabel: "Маршрут",
    routeSummaryTitle: "Коротка карта маршруту",
    summaryActivePrograms: "Активні програми",
    summaryCompletedPrograms: "Завершені маршрути",
    summaryProducts: "Продукти в профілі",
    summaryActiveProgramsValue: activePrograms > 0 ? `${activePrograms}` : "Поки немає",
    summaryCompletedProgramsValue: completedPrograms > 0 ? `${completedPrograms}` : "Поки немає",
    summaryProductsValue: productPurchases > 0 ? `${productPurchases}` : "Поки немає",
    programsLabel: "Програми",
    programsTitle: "Активні та завершені маршрути",
    activeProgramLabel: "Активна програма",
    completedProgramLabel: "Завершений маршрут",
    routeStarted: "Старт маршруту",
    purchasedAt: "Дата покупки",
    accessStatus: "Стан доступу",
    programProgressNote: "Тут уже видно доступ і стан маршруту, а детальний поступ уроків збирається в цю ж карту проходження.",
    programAccessManual: "Доступ підтверджено окремо",
    programAccessNoToken: "Маршрут був оформлений без окремого токена доступу",
    noProgramsLead: "Поки немає програм, прив’язаних до цього профілю.",
    productsTitle: "Куплені формати підтримки",
    productLabel: "Продукт",
    price: "Сума",
    productNoAccess: "Доступ готується",
    noProductsLead: "Куплених продуктів, прив’язаних до цього профілю, поки не знайдено.",
    progressLabel: "Поступ",
    progressTitle: "Проходження програм",
    progressLead: "Цей блок збирає вашу карту проходження: активні маршрути, завершені етапи і доречний наступний крок у платформі.",
    contactsTitle: "Збережені контактні поля",
    name: "Ім’я",
    email: "Email",
    phone: "Телефон",
    telegram: "Telegram",
    unavailableTitle: "Профіль тимчасово недоступний",
    unavailableLead: "У цій збірці персональний профіль тимчасово недоступний.",
    errorTitle: "Не вдалося зібрати профіль",
    errorFallback: "Спробуйте оновити сторінку трохи пізніше.",
    emptyValue: "—",
    doshaLabels: { vata: "Вата", pitta: "Пітта", kapha: "Капха" },
  };
}
