--
-- accounts referenced by content, re-created as local sign-ins
-- Generated by scripts/db-local.mjs — do not hand-edit.
--

-- Same ids as production so content foreign keys resolve; the emails and
-- the password are local inventions. Password for every account: local-dev

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at
) values (
  '00000000-0000-0000-0000-000000000000', 'a68003e9-e804-4d1c-96d0-08b2d770a6d6', 'authenticated', 'authenticated',
  'author1@local.test', crypt('local-dev', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now()
) on conflict (id) do nothing;

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at
) values (
  '00000000-0000-0000-0000-000000000000', 'bdc98ead-08d6-4869-ae09-cd154030e339', 'authenticated', 'authenticated',
  'author2@local.test', crypt('local-dev', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now()
) on conflict (id) do nothing;
