// GENERATED by scripts/icons-bake.mjs — do not edit.
// Geometry source: scripts/lib/icon-glyphs.mjs

export const CW_ICON_NAMES = [
  "arrow-right",
  "arrow-left",
  "chevron-right",
  "chevron-down",
  "body",
  "rhythm",
  "support",
  "day",
  "phase",
  "week",
  "clock",
  "check",
  "shield-check",
  "star",
  "price",
  "water",
  "leaf",
  "bowl",
  "stone",
  "breath",
  "sleep",
  "food",
  "motion",
  "play",
  "guide",
  "question",
  "boundary",
  "user",
  "lock",
  "globe",
  "sun",
  "moon",
  "mail",
  "phone",
  "telegram",
  "menu",
  "close",
  "vata",
  "pitta",
  "kapha",
] as const;

export const CW_GRAPHIC_NAMES = [
  "dot",
  "orbit",
  "rail",
  "connector",
] as const;

export type CwIconName = (typeof CW_ICON_NAMES)[number];
export type CwGraphicName = (typeof CW_GRAPHIC_NAMES)[number];
