import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { escapeHtml } from "@/lib/strings";

import { EMAIL_CATALOG } from "./catalog";

const GALLERY = join(process.cwd(), "docs", "design-system", "email-gallery.html");
const EMAIL_DIR = join(process.cwd(), "src", "lib", "email");

/** The hidden first line of the frame: what an inbox shows after the subject. */
function preheaderOf(html: string): string {
  const match = html.match(/<div style="display:none[^>]*>([^&<]*)/);
  return match?.[1]?.trim() ?? "";
}

function galleryHtml(): string {
  const cards = EMAIL_CATALOG.map((entry) => {
    const letter = entry.render();
    return `<section class="letter" id="${entry.id}">
  <header>
    <h2>${escapeHtml(entry.name)}</h2>
    <dl>
      <dt>Тема</dt><dd><b>${escapeHtml(letter.subject)}</b></dd>
      <dt>Прехедер</dt><dd>${escapeHtml(preheaderOf(letter.html)) || "—"}</dd>
      <dt>Коли</dt><dd>${escapeHtml(entry.trigger)}</dd>
      <dt>Хто шле</dt><dd>${entry.sender}</dd>
      <dt>Умова</dt><dd>${escapeHtml(entry.gate)}</dd>
      <dt>Код</dt><dd><code>${entry.source}</code></dd>
    </dl>
  </header>
  <iframe title="${escapeHtml(entry.name)}" loading="lazy" srcdoc="${escapeHtml(letter.html)}"></iframe>
</section>`;
  }).join("\n");

  return `<!doctype html>
<html lang="uk">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>CenterWay — листи</title>
<!-- GENERATED by npm run email:gallery from src/lib/email/catalog.ts. Do not edit by hand. -->
<style>
:root{--paper:#faefe0;--surface:#fff8ef;--ink:#18261d;--muted:#48544c;--border:#dcd4c6}
*{box-sizing:border-box}
body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.55 Manrope,'Segoe UI',system-ui,sans-serif}
main{max-width:1180px;margin:0 auto;padding:32px 16px 64px}
h1{font:600 34px/1.15 'Cormorant Garamond',Georgia,serif;margin:0 0 8px}
.lede{color:var(--muted);max-width:68ch;margin:0 0 28px}
nav{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 32px}
nav a{color:var(--ink);text-decoration:underline;text-decoration-color:var(--border);text-underline-offset:3px}
.letter{display:grid;grid-template-columns:minmax(0,360px) minmax(0,1fr);gap:24px;padding:24px 0;border-top:1px solid var(--border)}
.letter h2{font:600 24px/1.2 'Cormorant Garamond',Georgia,serif;margin:0 0 12px}
dl{display:grid;grid-template-columns:auto 1fr;gap:6px 12px;margin:0}
dt{color:var(--muted)}dd{margin:0}
code{font:13px/1.4 'IBM Plex Mono',ui-monospace,monospace;word-break:break-all}
iframe{width:100%;height:760px;border:1px solid var(--border);border-radius:16px;background:var(--paper)}
@media (max-width:820px){.letter{grid-template-columns:1fr}iframe{height:680px}}
</style>
</head>
<body>
<main>
<h1>Листи CenterWay</h1>
<p class="lede">Кожен лист, який надсилає платформа, з прикладовими даними, зібраний тим самим кодом, що й справжній. Одна рамка для всіх: папір, картка, марка і вордмарк, серифний заголовок, тепла кнопка. Опис рамки — docs/design-system.md, розділ «Email».</p>
<nav>${EMAIL_CATALOG.map((e) => `<a href="#${e.id}">${escapeHtml(e.name)}</a>`).join("")}</nav>
${cards}
</main>
</body>
</html>
`;
}

describe("email catalog", () => {
  it("renders every letter in the one frame", () => {
    for (const entry of EMAIL_CATALOG) {
      const { subject, html } = entry.render();
      expect(subject.trim(), entry.id).not.toBe("");
      expect(html, entry.id).toContain("cw-mark-ink@3x.png");
      expect(html, entry.id).toContain("cw-wordmark-ink@3x.png");
    }
  });

  it("has unique ids", () => {
    const ids = EMAIL_CATALOG.map((e) => e.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it("lists every builder in src/lib/email", () => {
    /* A file that exports a `build…Email`/`build…Template` is a letter; it must
       be in the catalog, or the design system does not know it exists. */
    const listed = new Set(EMAIL_CATALOG.map((e) => e.source));
    const builders = readdirSync(EMAIL_DIR).filter((file) => {
      if (!file.endsWith(".ts") || file.endsWith(".test.ts")) return false;
      return /export function build\w+(Email|Template)\b/.test(readFileSync(join(EMAIL_DIR, file), "utf8"));
    });
    for (const file of builders)
      expect(listed, `src/lib/email/${file} is not in catalog.ts`).toContain(`src/lib/email/${file}`);
  });

  it("matches the gallery in the design system", () => {
    const html = galleryHtml();
    if (process.env.CW_WRITE_EMAIL_GALLERY === "1") writeFileSync(GALLERY, html);
    expect(existsSync(GALLERY), "run npm run email:gallery").toBe(true);
    expect(readFileSync(GALLERY, "utf8"), "email-gallery.html drifted — run npm run email:gallery").toBe(html);
  });
});
