/**
 * Writes docs/README.md: an index of every Markdown file under docs/, grouped,
 * with each file's own first heading as its line. Run `npm run docs:index`
 * after adding a note; `npm run docs:index:check` fails when the index is
 * stale, the way tokens:check does for the generated CSS.
 *
 * The index is generated because a hand-kept one was tried (LOCAL_DOCS.md's
 * "active root set" of five files) and was 80 files behind within two months.
 * A list nobody has to maintain is the only list that stays true.
 */

import fs from "node:fs";
import path from "node:path";

const root = path.resolve(process.cwd(), "docs");
const out = path.join(root, "README.md");

const START_HERE = [
  ["CANON.md", "where the canon lives and what this folder is for"],
  ["LOCAL_DOCS.md", "how this folder is organised"],
  ["platform_agent_preflight.md", "the questions to answer before touching a public page"],
  ["adr/README.md", "decisions, one file each"],
  ["design-system.md", "the living design-system reference"],
  ["design-system/DESIGN_CONTRACT.md", "the code / mirror / brief contract"],
  ["migration/README.md", "how a schema change is made and journaled"],
];

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return walk(full);
    return entry.name.endsWith(".md") ? [full] : [];
  });
}

function heading(file) {
  const text = fs.readFileSync(file, "utf8");
  const match = /^#\s+(.+?)\s*$/m.exec(text);
  return (match ? match[1] : path.basename(file, ".md")).replace(/\s+/g, " ");
}

const files = walk(root)
  .map((full) => path.relative(root, full))
  .filter((rel) => rel !== "README.md")
  .sort();

const dated = (rel) => /(\d{4}-\d{2}-\d{2})/.exec(path.basename(rel))?.[1] ?? null;
const line = (rel) => `- [${heading(path.join(root, rel))}](${rel})`;

const groups = {
  "Decisions": files.filter((rel) => rel.startsWith("adr/") && rel !== "adr/README.md"),
  "Notes, newest first": files
    .filter((rel) => !rel.includes("/") && dated(rel) && !START_HERE.some(([f]) => f === rel))
    .sort((a, b) => dated(b).localeCompare(dated(a)) || a.localeCompare(b)),
  "Undated notes": files.filter((rel) => !rel.includes("/") && !dated(rel) && !START_HERE.some(([f]) => f === rel)),
  "Design system": files.filter((rel) => rel.startsWith("design-system/") && !START_HERE.some(([f]) => f === rel)),
  "Migrations": files.filter((rel) => rel.startsWith("migration/") && !START_HERE.some(([f]) => f === rel)),
  "Archive": files.filter((rel) => rel.startsWith("archive/")),
  "Raw": files.filter((rel) => rel.startsWith("raw/")),
};

const covered = new Set([...START_HERE.map(([f]) => f), ...Object.values(groups).flat()]);
const rest = files.filter((rel) => !covered.has(rel));
if (rest.length) groups["Other"] = rest;

const sections = [
  "# docs/",
  "",
  "Generated by `npm run docs:index` — do not edit by hand; add or rename a file and run it again.",
  `${files.length} files. Each line is the file's own first heading.`,
  "",
  "## Start here",
  "",
  ...START_HERE.filter(([f]) => fs.existsSync(path.join(root, f))).map(([f, why]) => `- [${heading(path.join(root, f))}](${f}) — ${why}`),
];
for (const [title, list] of Object.entries(groups)) {
  if (!list.length) continue;
  sections.push("", `## ${title}`, "", ...list.map(line));
}
const text = sections.join("\n") + "\n";

if (process.argv.includes("--check")) {
  const current = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : "";
  if (current !== text) {
    console.error("docs/README.md is stale — run `npm run docs:index`.");
    process.exit(1);
  }
  console.log("docs/README.md is current.");
} else {
  fs.writeFileSync(out, text);
  console.log(`docs/README.md: ${files.length} files indexed.`);
}
