#!/usr/bin/env node
// Exports the design-system bundle that the claude.ai Design project mirrors.
//
// Why this exists: the project's tokens/*.css used to be hand-copied from the
// repo, so it drifted the moment a value moved — by 2026-08-20 it was a whole
// redesign behind and carried a palette the code never had. Everything the
// bundle can derive is now derived here, from the same cw.tokens.json the app
// generates globals.css from. Hand-authored files in the project (components,
// ui_kits, guideline cards) are out of scope on purpose; only the token layer
// and the entry point are machine-owned.
//
//   npm run ds:export        write data/design-tokens/ds-bundle/**
//   npm run ds:sync:check    re-derive and fail if the bundle is stale or edited
//
// The manifest (_sync.json) carries a sha256 per file plus the token-source
// hash, and it is uploaded with the bundle. Reading that one small file from
// the project is enough to tell whether the mirror is current — no need to
// download and diff every file.

import { readFile, writeFile, mkdir, rm, readdir } from "node:fs/promises";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const TOKENS_PATH = path.join(repoRoot, "data", "design-tokens", "cw.tokens.json");
const OUT_DIR = path.join(repoRoot, "data", "design-tokens", "ds-bundle");
const FORMAT_VERSION = 1;

const GEOMETRY_PREFIXES = ["--cw-space-", "--cw-radius-", "--cw-card-", "--cw-shadow", "--cw-max-width", "--cw-border-width", "--ds-radius-"];
const TYPE_PREFIXES = ["--cw-font-"];
const isGeometry = (k) => GEOMETRY_PREFIXES.some((p) => k.startsWith(p));
const isType = (k) => TYPE_PREFIXES.some((p) => k.startsWith(p));

// A handful of roles carry a reason that is not visible in the value. The
// export keeps those reasons next to the tokens instead of leaving the mirror
// with a wall of hexes.
const ROLE_NOTES = {
  "--cw-sem-guide-primary": "the route voice. Deepened from the brand sheet's #588768, which sat at\n     3.64 against the CTA label and read bright next to the gold.",
  "--cw-sem-embodied": "the living green — practice marks, progress fills. Split off guide on\n     2026-08-20: the brand sheet had both roles on one value.",
  "--cw-sem-trust": "the only cool tone, and deliberately not a button colour — proof\n     panels, badges, curator links.",
  "--cw-sem-muted-ink": "body ink on light grounds. A mix off platform-text lands at 4.19 on\n     the cream ground, below body AA — hence a token, not a formula.",
  "--cw-platform-text": "one step deeper than method-ink: at #203126 the topbar label on the\n     chrome glass falls to 4.00 at the tone bound.",
  "--cw-platform-accent-contrast": "#faefe0 reads 4.44 on the dark-tone chrome glass, just under the bar.",
};

const decls = (map, indent = "  ") =>
  Object.entries(map)
    .map(([k, v]) => (ROLE_NOTES[k] ? `${indent}/* ${ROLE_NOTES[k]} */\n` : "") + `${indent}${k}: ${v};`)
    .join("\n");
const pick = (map, keep) => Object.fromEntries(Object.entries(map ?? {}).filter(([k]) => keep(k)));
const banner = (title, note) =>
  `/* ${title}\n   GENERATED by scripts/ds-export.mjs — do not edit by hand.\n   Source: data/design-tokens/cw.tokens.json\n\n   ${note}\n */\n`;

function buildFiles(tokens) {
  const { base = {}, layers = {}, delivery = {} } = tokens;
  const light = base.light ?? {};
  const chromeLight = pick(light, (k) => !isGeometry(k) && !isType(k));

  const files = {};

  files["tokens/primitives.css"] =
    banner("PRIMITIVES — raw colour anchors (layers.primitives.color).",
      "Components must not read these directly, only the --cw-sem-* roles above them.") +
    ":root {\n" +
    Object.entries(layers.primitives?.color ?? {})
      .map(([name, value]) => `  --cw-prim-${name.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase())}: ${value.toLowerCase()};`)
      .join("\n") +
    "\n}\n";

  files["tokens/colors.css"] =
    banner("COLOR — chrome base, semantic roles, platform modes, packs.",
      "Themes: :root light · [data-cw-theme=\"dark\"] dark — ONE pair for the whole\n   product since 2026-08-28. The admin's separate `.dark` class is retired; the\n   chrome family in :root is an alias layer over the platform and material\n   roles, so it flips with them and has no dark half of its own.") +
    `:root {\n${decls(chromeLight)}\n\n  /* semantic roles */\n${decls(layers.semanticAliases ?? {})}\n\n  /* platform mode */\n${decls(layers.modeOverrides?.platform ?? {})}\n}\n\n` +
    `[data-cw-theme="dark"] {\n${decls(layers.modeOverrides?.platformDark ?? {})}\n}\n\n` +
    Object.entries(layers.packs ?? {})
      .map(([name, map]) => `.cw-pack-${name} {\n${decls(map)}\n}\n`)
      .join("\n");

  files["tokens/geometry.css"] =
    banner("GEOMETRY — spacing, radii, card recipe, container.",
      "Values are exact and never snapped to a 4/8-px grid.") +
    `:root {\n${decls(pick(light, isGeometry))}\n}\n`;

  files["tokens/material.css"] =
    banner("MATERIAL — the tactile surface layer (layers.material).",
      "One warm grainy glass, its matte and inverse siblings. Cards are matte;\n   glass is chrome and panels over media. No inset top highlight — it reads\n   as gloss, not matte. One glass depth only; never nest glass in glass.") +
    `:root {\n${decls(layers.material?.light ?? {})}\n}\n\n` +
    `[data-cw-theme="dark"],\n[data-cw-header-tone="dark"] {\n${decls(layers.material?.dark ?? {})}\n}\n\n` +
    MATERIAL_RECIPE + LEGACY_SHIM;

  files["tokens/delivery.css"] =
    banner("DELIVERY — the --ds-* alias contract shared with the landings.", "") +
    `:root {\n${decls(delivery.dsAlias?.light ?? {})}\n}\n`;

  files["styles.css"] =
    "/* CenterWay Design System — entry point. @import lines only.\n" +
    "   GENERATED by scripts/ds-export.mjs — do not edit by hand. */\n" +
    ["fonts", "primitives", "colors", "material", "typography", "geometry", "delivery", "brand"]
      .map((n) => `@import "./tokens/${n}.css";`)
      .join("\n") + "\n";

  return files;
}

// The recipe is behaviour, not values — it rides along so the mirror renders
// the material rather than only declaring it.
const MATERIAL_RECIPE = `/* --- the recipe --------------------------------------------------- */

[data-cw-material] { position: relative; color: var(--cw-platform-text); }
[data-cw-material="matte"] { background-color: var(--cw-mat-surface); box-shadow: var(--cw-mat-shadow-soft); }

/* Never hand-write -webkit-backdrop-filter beside this: build pipelines
   collapse the pair into the prefixed property only, and Blink no longer
   honours that alias — which silently turns every glass off. */
[data-cw-material="glass"],
[data-cw-material="glass-media"] {
  backdrop-filter: var(--cw-mat-filter);
  border: 1px solid var(--cw-mat-stroke);
  box-shadow: var(--cw-mat-shadow-soft);
}
[data-cw-material="glass"] { background-color: var(--cw-mat-tint); }
[data-cw-material="glass-media"] { background-color: var(--cw-mat-tint-media); box-shadow: var(--cw-mat-shadow-raised); }
[data-cw-material="chrome"] {
  background-color: var(--cw-mat-tint-chrome);
  backdrop-filter: var(--cw-mat-filter);
  box-shadow: var(--cw-mat-shadow-chrome);
}
[data-cw-material="inverse"] {
  background: var(--cw-mat-inverse-bg);
  color: var(--cw-mat-inverse-text);
  border: 1px solid var(--cw-mat-inverse-stroke);
}
[data-cw-material]::before {
  content: "";
  position: absolute;
  inset: 0;
  border-radius: inherit;
  pointer-events: none;
  background-image: var(--cw-mat-grain-image);
}
[data-cw-material] > * { position: relative; }

/* Degradation is part of the contract: both fallbacks land on the opaque
   surface, whose contrast is strictly better than the glass it replaces. */
@supports not (backdrop-filter: blur(1px)) {
  [data-cw-material="glass"],
  [data-cw-material="glass-media"],
  [data-cw-material="chrome"] { background-color: var(--cw-mat-surface); }
}
@media (prefers-reduced-transparency: reduce) {
  [data-cw-material="glass"],
  [data-cw-material="glass-media"],
  [data-cw-material="chrome"] { background-color: var(--cw-mat-surface); backdrop-filter: none; }
}
`;

// Mirror-only. The depth and component-glass layers were retired in the
// product on 2026-08-15 and their 49 consumers moved onto --cw-mat-*. The
// project still has hand-authored components reading the old names, so the
// export ships them as aliases — never as definitions, and never back into
// globals.css.
const LEGACY_SHIM = `
/* --- compatibility (mirror only) ---------------------------------
   Retired in the product 2026-08-15. Present here solely so this
   project's older components keep rendering until they migrate.
   Do not use in new work; do not reintroduce in the repo. */
:root {
  --cw-depth-card-bg: var(--cw-mat-surface);
  --cw-depth-support-bg: var(--cw-mat-tone-support);
  --cw-depth-proof-bg: var(--cw-mat-tone-proof);
  --cw-depth-boundary-bg: var(--cw-mat-tone-boundary);
  --cw-depth-icon-slot-bg: var(--cw-mat-tone-icon);
  --cw-depth-rail-color: var(--cw-sem-progress);
  --cw-depth-shadow-soft: var(--cw-mat-shadow-soft);
  --cw-depth-shadow-medium: var(--cw-mat-shadow-raised);
  --cw-depth-shadow-strong: var(--cw-mat-shadow-deep);
  --cw-component-glass-bg: var(--cw-mat-tint);
  --cw-component-glass-bg-hover: var(--cw-mat-tint-hover);
  --cw-component-glass-border: var(--cw-mat-stroke);
  --cw-component-glass-filter: var(--cw-mat-filter);
  --cw-component-glass-shadow: var(--cw-mat-shadow-soft);
}
`;

const sha = (s) => createHash("sha256").update(s).digest("hex").slice(0, 16);

function headSha() {
  try {
    return execFileSync("git", ["rev-parse", "--short", "HEAD"], { cwd: repoRoot }).toString().trim();
  } catch {
    return "unknown";
  }
}

async function collect() {
  const raw = await readFile(TOKENS_PATH, "utf8");
  const files = buildFiles(JSON.parse(raw));
  const manifest = {
    formatVersion: FORMAT_VERSION,
    generator: "scripts/ds-export.mjs",
    sourceCommit: headSha(),
    tokensSource: sha(raw),
    files: Object.fromEntries(Object.keys(files).sort().map((p) => [p, sha(files[p])])),
  };
  files["_sync.json"] = JSON.stringify(manifest, null, 2) + "\n";
  return files;
}

async function readBundle() {
  const out = {};
  const walk = async (dir, prefix = "") => {
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      const rel = prefix ? `${prefix}/${e.name}` : e.name;
      if (e.isDirectory()) await walk(path.join(dir, e.name), rel);
      else out[rel] = await readFile(path.join(dir, e.name), "utf8");
    }
  };
  await walk(OUT_DIR);
  return out;
}

async function write(files) {
  await rm(OUT_DIR, { recursive: true, force: true });
  for (const [rel, body] of Object.entries(files)) {
    const target = path.join(OUT_DIR, rel);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, body, "utf8");
  }
}

const files = await collect();

if (process.argv.includes("--check")) {
  const onDisk = await readBundle();
  // sourceCommit moves with every commit and says nothing about drift.
  const strip = (s) => s.replace(/"sourceCommit": "[^"]*"/, '"sourceCommit": "-"');
  const problems = [];
  for (const [rel, body] of Object.entries(files)) {
    const have = onDisk[rel];
    if (have === undefined) problems.push(`missing: ${rel}`);
    else if (strip(have) !== strip(body)) problems.push(`stale or hand-edited: ${rel}`);
  }
  for (const rel of Object.keys(onDisk)) if (!(rel in files)) problems.push(`orphan: ${rel}`);

  if (problems.length) {
    console.error("[FAIL] DS bundle out of sync with cw.tokens.json");
    for (const p of problems) console.error(`  - ${p}`);
    console.error("\n  Run `npm run ds:export`, then push data/design-tokens/ds-bundle/** to the");
    console.error("  claude.ai Design project (see docs/design-system.md → Mirror protocol).");
    process.exit(1);
  }
  console.log(`[PASS] DS bundle in sync (${Object.keys(files).length} files)`);
} else {
  await write(files);
  console.log(`[ok] wrote data/design-tokens/ds-bundle/ (${Object.keys(files).length} files)`);
  for (const rel of Object.keys(files).sort()) console.log(`  ${rel}`);
}
