#!/usr/bin/env node
/**
 * Bakes the CenterWay icon + hand-graphics geometry into shipped sprites.
 *
 * WHY A BAKE STEP AT ALL
 * The approved "hand" character comes from the study in
 * docs/archive/working-notes/ds-icon-character-study-2026-08-15.html, where it
 * was produced at render time by feTurbulence + feDisplacementMap. That must
 * not ship: Safari pays for a filter per icon instance and small glyphs go
 * mushy. So the wobble is applied once, here, at build time.
 *
 * HOW (and how it differs from the study)
 * feDisplacementMap is a RASTER operation — it cannot be "baked into a path".
 * Baking it geometrically instead: each path is resampled with the browser's
 * own getPointAtLength (so arcs and curves are handled exactly), every sample
 * is pushed by a seeded 2D value-noise field with the same period and
 * amplitude as the preset (baseFrequency -> noise period, scale -> amplitude),
 * and the displaced samples are re-emitted as smooth cubics. Same character,
 * real vector output, deterministic across runs.
 *
 * Usage:
 *   node scripts/icons-bake.mjs                 # bake preset hand2, write sprites
 *   node scripts/icons-bake.mjs --preset hand1
 *   node scripts/icons-bake.mjs --check         # fail if output differs from disk
 */

import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { bakeSprites } from "./lib/icon-bake-core.mjs";
import { ICONS, GRAPHICS, HAND_PRESETS, DEFAULT_PRESET } from "./lib/icon-glyphs.mjs";

const ROOT = path.resolve(import.meta.dirname, "..");

/** Sprites are emitted twice: the platform reads one, funnel hosts the other. */
const TARGETS = [
  path.join(ROOT, "public/cw/icons/cw-icons.svg"),
  path.join(ROOT, "src/landing-static/shared/img/cw-icons.svg"),
];

function parseArgs(argv) {
  const args = { preset: DEFAULT_PRESET, check: false };
  for (let i = 2; i < argv.length; i += 1) {
    if (argv[i] === "--preset") args.preset = argv[++i];
    else if (argv[i] === "--check") args.check = true;
    else throw new Error(`unknown argument: ${argv[i]}`);
  }
  if (!HAND_PRESETS[args.preset]) {
    throw new Error(`unknown preset "${args.preset}" (have: ${Object.keys(HAND_PRESETS).join(", ")})`);
  }
  return args;
}

/** The name union is generated too, so a typo in <Icon name> fails typecheck. */
const NAMES_TARGET = path.join(ROOT, "src/components/iconNames.ts");

function namesModule() {
  const list = (names) => names.map((n) => `  "${n}",`).join("\n");
  return `// GENERATED by scripts/icons-bake.mjs — do not edit.
// Geometry source: scripts/lib/icon-glyphs.mjs

export const CW_ICON_NAMES = [
${list(Object.keys(ICONS))}
] as const;

export const CW_GRAPHIC_NAMES = [
${list(Object.keys(GRAPHICS))}
] as const;

export type CwIconName = (typeof CW_ICON_NAMES)[number];
export type CwGraphicName = (typeof CW_GRAPHIC_NAMES)[number];
`;
}

async function main() {
  const args = parseArgs(process.argv);
  const { sprite } = (await bakeSprites([args.preset])).get(args.preset);

  const outputs = [
    ...TARGETS.map((target) => ({ target, content: sprite })),
    { target: NAMES_TARGET, content: namesModule() },
  ];

  let drift = false;
  for (const { target, content } of outputs) {
    const existing = await fs.readFile(target, "utf8").catch(() => null);
    if (existing === content) continue;
    if (args.check) {
      drift = true;
      console.error(`drift: ${path.relative(ROOT, target)} does not match the baked output`);
      continue;
    }
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, content);
    console.log(`wrote ${path.relative(ROOT, target)}`);
  }

  const counts = `${Object.keys(ICONS).length} glyphs + ${Object.keys(GRAPHICS).length} graphics`;
  if (args.check) {
    if (drift) process.exit(1);
    console.log(`icons:check ok — ${counts}, preset ${args.preset}`);
  } else {
    console.log(`baked ${counts} with preset ${args.preset}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
