#!/usr/bin/env node
/**
 * Bakes the CenterWay icon + hand-graphics geometry into shipped sprites.
 *
 * WHY A BAKE STEP AT ALL
 * The approved "hand" character comes from the study in
 * docs/archive/working-notes/ds-icon-character-study-2026-08-15.html, where it
 * was produced at render time by feTurbulence + feDisplacementMap. That must
 * not ship: Safari pays for a filter per icon instance and small glyphs go
 * mushy. So the wobble is applied once, here, at build time.
 *
 * HOW (and how it differs from the study)
 * feDisplacementMap is a RASTER operation — it cannot be "baked into a path".
 * Baking it geometrically instead: each path is resampled with the browser's
 * own getPointAtLength (so arcs and curves are handled exactly), every sample
 * is pushed by a seeded 2D value-noise field with the same period and
 * amplitude as the preset (baseFrequency -> noise period, scale -> amplitude),
 * and the displaced samples are re-emitted as smooth cubics. Same character,
 * real vector output, deterministic across runs.
 *
 * A WRITE NEVER DROPS A SYMBOL BY ACCIDENT (2026-09-11). The sprite on disk
 * carried `cw-ink-rule`, which had no definition left in icon-glyphs.mjs — so
 * `npm run icons:build` would have quietly removed a symbol that ships and that
 * InteractionInk.tsx renders, and nothing would have said so until the mark
 * stopped drawing in production. Losing a glyph is a refusal now, with the
 * names in it. `--allow-drop` is how you say you meant it.
 *
 * Usage:
 *   node scripts/icons-bake.mjs                 # bake preset hand2, write sprites
 *   node scripts/icons-bake.mjs --preset hand1
 *   node scripts/icons-bake.mjs --check         # fail if output differs from disk
 *   node scripts/icons-bake.mjs --allow-drop    # write even if a symbol disappears
 */

import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import process from "node:process";
import { bakeSprites } from "./lib/icon-bake-core.mjs";
import { ICONS, GRAPHICS, HAND_PRESETS, DEFAULT_PRESET } from "./lib/icon-glyphs.mjs";

const ROOT = path.resolve(import.meta.dirname, "..");

/** Sprites are emitted twice: the platform reads one, funnel hosts the other. */
const TARGETS = [
  path.join(ROOT, "public/cw/icons/cw-icons.svg"),
  path.join(ROOT, "src/landing-static/shared/img/cw-icons.svg"),
];

function parseArgs(argv) {
  const args = { preset: DEFAULT_PRESET, check: false, allowDrop: false };
  for (let i = 2; i < argv.length; i += 1) {
    if (argv[i] === "--preset") args.preset = argv[++i];
    else if (argv[i] === "--check") args.check = true;
    else if (argv[i] === "--allow-drop") args.allowDrop = true;
    else throw new Error(`unknown argument: ${argv[i]}`);
  }
  if (!HAND_PRESETS[args.preset]) {
    throw new Error(`unknown preset "${args.preset}" (have: ${Object.keys(HAND_PRESETS).join(", ")})`);
  }
  return args;
}

/** The name union is generated too, so a typo in <Icon name> fails typecheck. */
const NAMES_TARGET = path.join(ROOT, "src/lib/brand/iconNames.ts");

/**
 * THE SPRITE'S CONTENT HASH, AND WHY THE URL NEEDS ONE.
 *
 * `cw-icons.svg` is served with a week of `max-age` (next.config.ts explains
 * the bill that bought), and it is referenced BY ID: `<use href="…#cw-menu">`.
 * Those two facts are compatible right up until the set of ids changes. On
 * 2026-09-11 `cw-ink-rule` was added and every ink mark on the site began
 * pointing at it — and for everyone holding a week-old sprite that `<use>`
 * resolved to nothing. No error, no fallback, no empty box: a missing target
 * simply paints nothing, so the marks vanished and looked like a CSS bug.
 *
 * A hash in the query is the smallest thing that fixes it. A changed sprite is
 * a changed URL, so the cache cannot serve yesterday's ids for today's markup,
 * and the week of caching stays intact for everyone whose sprite is current.
 * next.config.ts calls for hashing the FILENAME, which is the same idea one
 * step further; this stops short of it because the filename is also written
 * into five static landings that this bake does not own.
 */
function spriteVersion(sprite) {
  return crypto.createHash("sha256").update(sprite).digest("hex").slice(0, 8);
}

function namesModule(sprite) {
  const list = (names) => names.map((n) => `  "${n}",`).join("\n");
  return `// GENERATED by scripts/icons-bake.mjs — do not edit.
// Geometry source: scripts/lib/icon-glyphs.mjs

// Cache key for the sprite URL — see spriteVersion() in scripts/icons-bake.mjs.
export const CW_SPRITE_VERSION = "${spriteVersion(sprite)}";

export const CW_ICON_NAMES = [
${list(Object.keys(ICONS))}
] as const;

export const CW_GRAPHIC_NAMES = [
${list(Object.keys(GRAPHICS))}
] as const;

export type CwIconName = (typeof CW_ICON_NAMES)[number];
export type CwGraphicName = (typeof CW_GRAPHIC_NAMES)[number];
`;
}

const symbolIds = (svg) => new Set([...svg.matchAll(/<symbol id="([^"]+)"/g)].map((match) => match[1]));

/**
 * Every symbol the sprite on disk has and the fresh bake does not.
 *
 * A missing definition and a deliberate deletion look identical in the output;
 * they are told apart by whether the author says so. Defaulting to "this is a
 * mistake" is right because the mistake ships and the deletion is one flag away.
 */
async function droppedSymbols(sprite) {
  const dropped = new Set();
  const baked = symbolIds(sprite);
  for (const target of TARGETS) {
    const existing = await fs.readFile(target, "utf8").catch(() => null);
    if (!existing) continue;
    for (const id of symbolIds(existing)) if (!baked.has(id)) dropped.add(id);
  }
  return [...dropped].sort();
}

async function main() {
  const args = parseArgs(process.argv);
  const { sprite } = (await bakeSprites([args.preset])).get(args.preset);

  if (!args.check && !args.allowDrop) {
    const dropped = await droppedSymbols(sprite);
    if (dropped.length > 0) {
      console.error(
        `refusing to write: the bake would remove ${dropped.length} symbol(s) the sprite ships — ` +
          `${dropped.join(", ")}.\n` +
          "Either the geometry is missing from scripts/lib/icon-glyphs.mjs, or the glyph was retired.\n" +
          "Check what still renders it, then re-run with --allow-drop if the removal is intended.",
      );
      process.exit(1);
    }
  }

  const outputs = [
    ...TARGETS.map((target) => ({ target, content: sprite })),
    { target: NAMES_TARGET, content: namesModule(sprite) },
  ];

  let drift = false;
  for (const { target, content } of outputs) {
    const existing = await fs.readFile(target, "utf8").catch(() => null);
    if (existing === content) continue;
    if (args.check) {
      drift = true;
      console.error(`drift: ${path.relative(ROOT, target)} does not match the baked output`);
      continue;
    }
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, content);
    console.log(`wrote ${path.relative(ROOT, target)}`);
  }

  const counts = `${Object.keys(ICONS).length} glyphs + ${Object.keys(GRAPHICS).length} graphics`;
  if (args.check) {
    if (drift) process.exit(1);
    console.log(`icons:check ok — ${counts}, preset ${args.preset}`);
  } else {
    console.log(`baked ${counts} with preset ${args.preset}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
