// generated by scripts/generator-build-snapshots.mjs
export const cwGeneratorSnapshots = [
  {
    "branch": "consult",
    "experiment_key": "consult_theme_v1",
    "id": "consult-control",
    "mode": "consult",
    "route_key": "consult",
    "screen_id": "screen.consult.v1.control",
    "screen_version": "1.1.0",
    "variant_key": "control"
  },
  {
    "branch": "consult",
    "experiment_key": "consult_theme_v1",
    "id": "consult-warm-route",
    "mode": "consult",
    "route_key": "consult",
    "screen_id": "screen.consult.v1.warm_route",
    "screen_version": "1.1.0",
    "variant_key": "warm_route"
  },
  {
    "branch": "detox",
    "experiment_key": null,
    "id": "detox-control",
    "mode": "detox",
    "route_key": "detox",
    "screen_id": "screen.detox.v1.control",
    "screen_version": "1.1.0",
    "variant_key": null
  },
  {
    "branch": "herbs",
    "experiment_key": null,
    "id": "herbs-control",
    "mode": "herbs",
    "route_key": "herbs",
    "screen_id": "screen.herbs.v1.control",
    "screen_version": "1.1.0",
    "variant_key": null
  },
  {
    "branch": "platform",
    "experiment_key": "dosha_ui_variant_v1",
    "id": "dosha-control",
    "mode": "support",
    "route_key": "dosha-test",
    "screen_id": "screen.dosha-test.v1.control",
    "screen_version": "1.1.0",
    "variant_key": "control"
  },
  {
    "branch": "platform",
    "experiment_key": "dosha_ui_variant_v1",
    "id": "dosha-routecopy",
    "mode": "support",
    "route_key": "dosha-test",
    "screen_id": "screen.dosha-test.v1.routecopy",
    "screen_version": "1.1.0",
    "variant_key": "routecopy"
  },
  {
    "branch": "platform",
    "experiment_key": null,
    "id": "lesson-pilot-control",
    "mode": "lesson",
    "route_key": "lesson-pilot",
    "screen_id": "screen.lesson.pilot.v1.control",
    "screen_version": "1.0.0",
    "variant_key": null
  }
] as const;
